name: VS 2022

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: 0 4 * * WED
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2025

    strategy:
      matrix:
        configuration: ["release", "debug"]
        platform: ["win32", "x64"]

    steps:
      - uses: reupen/github-actions/.github/actions/prepare-msbuild-vcpkg@v1
        name: Prepare MSBuild and vcpkg

      - name: Build component
        run: |
          msbuild /m '/p:Platform=${{ matrix.platform }};Configuration=${{ matrix.configuration }}' "/logger:$Env:Temp\Reupen.MSBuild.GitHubLogger.dll" vc17\console_panel.sln

      - uses: actions/upload-artifact@v5
        name: Upload component artefact
        if: matrix.configuration == 'release'
        with:
          name: Component package (${{ matrix.configuration }}, ${{ matrix.platform }})
          path: vc17\release-*\*.fb2k-component

      - uses: actions/upload-artifact@v5
        name: Upload symbols artefact
        if: matrix.configuration == 'release'
        with:
          name: Symbols for debugging (${{ matrix.configuration }}, ${{ matrix.platform }})
          path: vc17\release-*\*.pdb

  test:
    runs-on: windows-2025

    strategy:
      matrix:
        configuration: ["debug"]
        platform: ["win32", "x64"]

    steps:
      - uses: reupen/github-actions/.github/actions/prepare-msbuild-vcpkg@v1
        name: Prepare MSBuild and vcpkg

      - name: Build tests
        run: |
          msbuild /m '/p:Platform=${{ matrix.platform }};Configuration=${{ matrix.configuration }}-test' "/logger:$Env:Temp\Reupen.MSBuild.GitHubLogger.dll" vc17\console_panel.sln

      - name: Run tests
        run: |
          Invoke-Expression '.\vc17\${{ matrix.configuration }}-${{ matrix.platform }}-v143\tests.exe'
